### ISSUE TITLE
Is it possible to somehow specify aspect ratio of the crops?

### ISSUE THREAD

**Issue by sobek1886** [bcmi/Human-Centric-Image-Cropping#2]
I tried using a subset of anchors in pdefined_anchors.pkl which match my specified aspect ratio (1:1) by adapting the get_pdefined_anchor() function in test.py
```def get_pdefined_anchor(make_square = False):
    # get predefined boxes(x1, y1, x2, y2)
    pdefined_anchors = np.array(pickle.load(open(cfg.predefined_pkl, 'rb'), encoding='iso-8859-1')).astype(np.float32)
    if make_square == True:
      filtered_indexes = [index for index, coord in enumerate(pdefined_anchors) if np.isclose(coord[2] - coord[0], coord[3] - coord[1])]
      filtered_anchors = pdefined_anchors[filtered_indexes]
      print('only square anchors')
      print('num of pre-defined anchors: ', filtered_anchors.shape)
      return filtered_anchors
    else:
      print('num of pre-defined anchors: ', pdefined_anchors.shape)
      return pdefined_anchors
```

This filtering seems to work, but even when solely using 1:1 anchors I get crops which are not 1:1.

**Comment by bo-zhang-cs** [comment]
Of course! Apart from using these predefined candidates, you can also generate candidates with specified aspect ratio by yourself. An example code can be found at this [[link]](https://github.com/bo-zhang-cs/GAIC-Pytorch/blob/877d6a325943c0a098324dc6d4a975ff4097c3f6/dataset/candidate_generation.py#L27).
